name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Build Docker image
      run: |
        cd backend
        docker build -t robin-backend .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: robinbackend
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: backend
